CREATE TABLE PascalCaseFooBar (
  Id        BIGINT IDENTITY,
  Foo NVARCHAR(20) NOT NULL,
  Bar  NVARCHAR(20) NOT NULL,
  CONSTRAINT PK_PascalCaseFooBar PRIMARY KEY (Id)
);

CREATE TABLE camelCaseFooBar (
  id        BIGINT IDENTITY,
  foo NVARCHAR(20) NOT NULL,
  bar  NVARCHAR(20) NOT NULL,
  CONSTRAINT PK_camelCaseFooBar PRIMARY KEY (Id)
);